show databases;
create database task_management;
use task_management;
show tables;
desc user;
desc project;
desc task;
select * from user;
select * from project;
select * from task;
delete from user;
delete from task;
delete from project;
drop database task_management;